-   id: lint-jenkinsfile
    name: Lint Jenkinsfile(s)
    description: This hook validates Jenkins declarative pipeline files using a Jenkins server.
    entry: lint-jenkinsfile
    language: python
    files: ^[Jj]enkins[fF]ile
    types: [text]
    require_serial: false
